# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/corax/Projects/WorkoutCalendar

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/corax/Projects/WorkoutCalendar

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/corax/Projects/WorkoutCalendar/CMakeFiles /home/corax/Projects/WorkoutCalendar//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/corax/Projects/WorkoutCalendar/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named WorkoutCalendar

# Build rule for target.
WorkoutCalendar: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WorkoutCalendar
.PHONY : WorkoutCalendar

# fast build rule for target.
WorkoutCalendar/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WorkoutCalendar.dir/build.make CMakeFiles/WorkoutCalendar.dir/build
.PHONY : WorkoutCalendar/fast

#=============================================================================
# Target rules for targets named WorkoutCalendar_autogen_timestamp_deps

# Build rule for target.
WorkoutCalendar_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WorkoutCalendar_autogen_timestamp_deps
.PHONY : WorkoutCalendar_autogen_timestamp_deps

# fast build rule for target.
WorkoutCalendar_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WorkoutCalendar_autogen_timestamp_deps.dir/build.make CMakeFiles/WorkoutCalendar_autogen_timestamp_deps.dir/build
.PHONY : WorkoutCalendar_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named WorkoutCalendar_autogen

# Build rule for target.
WorkoutCalendar_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WorkoutCalendar_autogen
.PHONY : WorkoutCalendar_autogen

# fast build rule for target.
WorkoutCalendar_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WorkoutCalendar_autogen.dir/build.make CMakeFiles/WorkoutCalendar_autogen.dir/build
.PHONY : WorkoutCalendar_autogen/fast

WorkoutCalendar_autogen/EWIEGA46WW/qrc_resources.o: WorkoutCalendar_autogen/EWIEGA46WW/qrc_resources.cpp.o
.PHONY : WorkoutCalendar_autogen/EWIEGA46WW/qrc_resources.o

# target to build an object file
WorkoutCalendar_autogen/EWIEGA46WW/qrc_resources.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WorkoutCalendar.dir/build.make CMakeFiles/WorkoutCalendar.dir/WorkoutCalendar_autogen/EWIEGA46WW/qrc_resources.cpp.o
.PHONY : WorkoutCalendar_autogen/EWIEGA46WW/qrc_resources.cpp.o

WorkoutCalendar_autogen/EWIEGA46WW/qrc_resources.i: WorkoutCalendar_autogen/EWIEGA46WW/qrc_resources.cpp.i
.PHONY : WorkoutCalendar_autogen/EWIEGA46WW/qrc_resources.i

# target to preprocess a source file
WorkoutCalendar_autogen/EWIEGA46WW/qrc_resources.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WorkoutCalendar.dir/build.make CMakeFiles/WorkoutCalendar.dir/WorkoutCalendar_autogen/EWIEGA46WW/qrc_resources.cpp.i
.PHONY : WorkoutCalendar_autogen/EWIEGA46WW/qrc_resources.cpp.i

WorkoutCalendar_autogen/EWIEGA46WW/qrc_resources.s: WorkoutCalendar_autogen/EWIEGA46WW/qrc_resources.cpp.s
.PHONY : WorkoutCalendar_autogen/EWIEGA46WW/qrc_resources.s

# target to generate assembly for a file
WorkoutCalendar_autogen/EWIEGA46WW/qrc_resources.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WorkoutCalendar.dir/build.make CMakeFiles/WorkoutCalendar.dir/WorkoutCalendar_autogen/EWIEGA46WW/qrc_resources.cpp.s
.PHONY : WorkoutCalendar_autogen/EWIEGA46WW/qrc_resources.cpp.s

WorkoutCalendar_autogen/mocs_compilation.o: WorkoutCalendar_autogen/mocs_compilation.cpp.o
.PHONY : WorkoutCalendar_autogen/mocs_compilation.o

# target to build an object file
WorkoutCalendar_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WorkoutCalendar.dir/build.make CMakeFiles/WorkoutCalendar.dir/WorkoutCalendar_autogen/mocs_compilation.cpp.o
.PHONY : WorkoutCalendar_autogen/mocs_compilation.cpp.o

WorkoutCalendar_autogen/mocs_compilation.i: WorkoutCalendar_autogen/mocs_compilation.cpp.i
.PHONY : WorkoutCalendar_autogen/mocs_compilation.i

# target to preprocess a source file
WorkoutCalendar_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WorkoutCalendar.dir/build.make CMakeFiles/WorkoutCalendar.dir/WorkoutCalendar_autogen/mocs_compilation.cpp.i
.PHONY : WorkoutCalendar_autogen/mocs_compilation.cpp.i

WorkoutCalendar_autogen/mocs_compilation.s: WorkoutCalendar_autogen/mocs_compilation.cpp.s
.PHONY : WorkoutCalendar_autogen/mocs_compilation.s

# target to generate assembly for a file
WorkoutCalendar_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WorkoutCalendar.dir/build.make CMakeFiles/WorkoutCalendar.dir/WorkoutCalendar_autogen/mocs_compilation.cpp.s
.PHONY : WorkoutCalendar_autogen/mocs_compilation.cpp.s

datelist.o: datelist.cpp.o
.PHONY : datelist.o

# target to build an object file
datelist.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WorkoutCalendar.dir/build.make CMakeFiles/WorkoutCalendar.dir/datelist.cpp.o
.PHONY : datelist.cpp.o

datelist.i: datelist.cpp.i
.PHONY : datelist.i

# target to preprocess a source file
datelist.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WorkoutCalendar.dir/build.make CMakeFiles/WorkoutCalendar.dir/datelist.cpp.i
.PHONY : datelist.cpp.i

datelist.s: datelist.cpp.s
.PHONY : datelist.s

# target to generate assembly for a file
datelist.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WorkoutCalendar.dir/build.make CMakeFiles/WorkoutCalendar.dir/datelist.cpp.s
.PHONY : datelist.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WorkoutCalendar.dir/build.make CMakeFiles/WorkoutCalendar.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WorkoutCalendar.dir/build.make CMakeFiles/WorkoutCalendar.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WorkoutCalendar.dir/build.make CMakeFiles/WorkoutCalendar.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.o: mainwindow.cpp.o
.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WorkoutCalendar.dir/build.make CMakeFiles/WorkoutCalendar.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i
.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WorkoutCalendar.dir/build.make CMakeFiles/WorkoutCalendar.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s
.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WorkoutCalendar.dir/build.make CMakeFiles/WorkoutCalendar.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

schedule.o: schedule.cpp.o
.PHONY : schedule.o

# target to build an object file
schedule.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WorkoutCalendar.dir/build.make CMakeFiles/WorkoutCalendar.dir/schedule.cpp.o
.PHONY : schedule.cpp.o

schedule.i: schedule.cpp.i
.PHONY : schedule.i

# target to preprocess a source file
schedule.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WorkoutCalendar.dir/build.make CMakeFiles/WorkoutCalendar.dir/schedule.cpp.i
.PHONY : schedule.cpp.i

schedule.s: schedule.cpp.s
.PHONY : schedule.s

# target to generate assembly for a file
schedule.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WorkoutCalendar.dir/build.make CMakeFiles/WorkoutCalendar.dir/schedule.cpp.s
.PHONY : schedule.cpp.s

scheduledock.o: scheduledock.cpp.o
.PHONY : scheduledock.o

# target to build an object file
scheduledock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WorkoutCalendar.dir/build.make CMakeFiles/WorkoutCalendar.dir/scheduledock.cpp.o
.PHONY : scheduledock.cpp.o

scheduledock.i: scheduledock.cpp.i
.PHONY : scheduledock.i

# target to preprocess a source file
scheduledock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WorkoutCalendar.dir/build.make CMakeFiles/WorkoutCalendar.dir/scheduledock.cpp.i
.PHONY : scheduledock.cpp.i

scheduledock.s: scheduledock.cpp.s
.PHONY : scheduledock.s

# target to generate assembly for a file
scheduledock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WorkoutCalendar.dir/build.make CMakeFiles/WorkoutCalendar.dir/scheduledock.cpp.s
.PHONY : scheduledock.cpp.s

topmenu.o: topmenu.cpp.o
.PHONY : topmenu.o

# target to build an object file
topmenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WorkoutCalendar.dir/build.make CMakeFiles/WorkoutCalendar.dir/topmenu.cpp.o
.PHONY : topmenu.cpp.o

topmenu.i: topmenu.cpp.i
.PHONY : topmenu.i

# target to preprocess a source file
topmenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WorkoutCalendar.dir/build.make CMakeFiles/WorkoutCalendar.dir/topmenu.cpp.i
.PHONY : topmenu.cpp.i

topmenu.s: topmenu.cpp.s
.PHONY : topmenu.s

# target to generate assembly for a file
topmenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WorkoutCalendar.dir/build.make CMakeFiles/WorkoutCalendar.dir/topmenu.cpp.s
.PHONY : topmenu.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... WorkoutCalendar_autogen"
	@echo "... WorkoutCalendar_autogen_timestamp_deps"
	@echo "... WorkoutCalendar"
	@echo "... WorkoutCalendar_autogen/EWIEGA46WW/qrc_resources.o"
	@echo "... WorkoutCalendar_autogen/EWIEGA46WW/qrc_resources.i"
	@echo "... WorkoutCalendar_autogen/EWIEGA46WW/qrc_resources.s"
	@echo "... WorkoutCalendar_autogen/mocs_compilation.o"
	@echo "... WorkoutCalendar_autogen/mocs_compilation.i"
	@echo "... WorkoutCalendar_autogen/mocs_compilation.s"
	@echo "... datelist.o"
	@echo "... datelist.i"
	@echo "... datelist.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
	@echo "... schedule.o"
	@echo "... schedule.i"
	@echo "... schedule.s"
	@echo "... scheduledock.o"
	@echo "... scheduledock.i"
	@echo "... scheduledock.s"
	@echo "... topmenu.o"
	@echo "... topmenu.i"
	@echo "... topmenu.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

